services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: aperisolve_web
    volumes:
      - aperisolve-data:/app/static/uploads
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aperisolve_back
    volumes:
      - aperisolve-data:/app/uploads
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - backend
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    env_file:
      - .env
    volumes:
      - aperisolve-db:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  aperisolve-data: # All uploads will be stored in this volume
  aperisolve-db: # All mongo db related data will be stored in this volume
  